services:
  # Frontend
  frontend:
    build: ./frontend
    develop:
      watch:
        - action: sync # sincroniza cambios sin reconstruir
          path: ./frontend/src
          target: /app/src
          initial_sync: true
          ignore:
            - node_modules/
        - action: sync # actualiza index.html
          path: ./frontend/index.html
          target: /app/index.html
          initial_sync: true
        - action: rebuild # al actualizar dependencias se debe reconstruir
          path: ./frontend/package.json
    container_name: app-container
    env_file:
      - .env
    ports:
      - 5173:5173
    depends_on: # Inicia backend primero, luego frontend
      - backend

  # Backend
  backend:
    build: ./backend
    develop:
      watch:
        - action: sync # carpeta src
          path: ./backend/src
          target: /app/src
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild # para actualizar dependencias
          path: ./backend/package.json
    container_name: api-container
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on: # Inicia primero la base de datos, luego el backend
      - db

  # Base de datos (PostgreSQL)
  db:
    image: postgres:18-alpine
    container_name: db-container
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - data:/var/lib/postgresql

volumes:
  data:
